name: Create torrent
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
env:
  name: "holoiso-installer_snapshot"
  comment: "holoiso-installer_snapshot20240901.1748.45_beta"
  url: "https://cd2.holoiso.ru.eu.org/holoiso-installer/beta/holoiso-installer_snapshot20240901.1748.45_beta-20240928153932-x86_64.iso"
  file_name: "holoiso-installer_snapshot20240901.1748.45_beta-20240928153932-x86_64.iso"
  piece_size: 21 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -v -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
